# Generated by Django 4.2.1 on 2023-06-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_ciudad_customuser_codigo_postal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asiento',
            name='precio',
        ),
        migrations.AddField(
            model_name='vuelo',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=10),
            preserve_default=False,
        ),
    ]
