# Generated by Django 4.2.1 on 2023-06-04 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
