# Generated by Django 4.2.1 on 2023-06-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_asiento_precio_vuelo_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='precio_total',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
