# Generated by Django 4.2.1 on 2023-06-11 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_vuelo_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='vuelo',
            name='imagen',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
