# Generated by Django 4.2.1 on 2023-06-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_vuelo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='vuelo',
            name='asientos_disponibles',
            field=models.PositiveIntegerField(default=200),
            preserve_default=False,
        ),
    ]
