# Generated by Django 4.2.1 on 2023-06-16 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_vuelo_asientos_disponibles'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraRealizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='compra',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='vuelo',
        ),
        migrations.RemoveField(
            model_name='vuelo',
            name='asientos_disponibles',
        ),
        migrations.AddField(
            model_name='carritocompra',
            name='monto',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='total_asientos',
            field=models.PositiveIntegerField(default=180),
        ),
        migrations.AlterField(
            model_name='carritocompra',
            name='cantidad_asientos',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Asiento',
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
        migrations.AddField(
            model_name='comprarealizada',
            name='carrito_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.carritocompra'),
        ),
        migrations.AddField(
            model_name='comprarealizada',
            name='pago_realizado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pago'),
        ),
    ]
