# Generated by Django 4.2.1 on 2023-06-16 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_comprarealizada_remove_compra_usuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comprarealizada',
            old_name='carrito_pago',
            new_name='carrito_comprado',
        ),
    ]
