# Generated by Django 4.2.1 on 2023-06-19 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_customuser_username'),
        ('api', '0009_compra_asiento'),
    ]

    operations = [
    ]
