# Generated by Django 4.2.1 on 2023-06-16 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_carrito_pago_comprarealizada_carrito_comprado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprarealizada',
            name='carrito_comprado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_realizadas', to='api.carritocompra'),
        ),
        migrations.AlterField(
            model_name='comprarealizada',
            name='pago_realizado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_realizadas', to='api.pago'),
        ),
    ]
