# Generated by Django 4.2.1 on 2023-06-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_merge_20230619_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='Asiento',
        ),
        migrations.AlterField(
            model_name='compra',
            name='cantidad_asientos',
            field=models.PositiveIntegerField(),
        ),
    ]
