# Generated by Django 4.2.1 on 2023-09-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_compra_asiento_alter_compra_cantidad_asientos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vuelo',
            name='asientos_disponibles',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
