# Generated by Django 4.2.1 on 2023-05-04 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cordoba_fly', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(max_length=100, unique=True)),
                ('contrasena', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cordoba_fly.pago'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='cantidad_asientos',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='compra',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cordoba_fly.usuario'),
        ),
    ]
